In [ ]:
import numpy as np
#creating an array
arr=np.array([1,2,3],dtype=float)
print(arr)


[1. 2. 3.]


In [ ]:
arrange=np.arange(5)
print(arrange)#arranges the array in the sorted order

[0 1 2 3 4]


In [ ]:
zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)#printing the matrix with all the zeros

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_arr=np.ones((2,2),dtype=float)
print(ones_arr)#printing the matrix with all the ones

[[1. 1.]
 [1. 1.]]


In [ ]:
#array manipulation
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)#reshaping th array

In [ ]:
arrange1=np.arange(0,100,5)
print(arrange1)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
data=np.savetxt("/content/sample.txt",arrange1)

In [ ]:
arrange1=np.arange(0,100,5)
print(arrange1)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
array1=np.array([1,2,3,4,5])
print(array1[2:4])#printing the elements in the sequence

[3 4]


In [ ]:
b=array1.T
print(b)#transposing a matrix

[1 2 3 4 5]


In [ ]:
a1=np.array([1,2,3,4,5,6,7,8])
c=np.split(a1,2)#splitting an array
print(c)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)#matrix multiplication
print(c)


[[19 22]
 [43 50]]


In [ ]:
d=np.linalg.eig(c)#printing  the eigen vlaues
print(d)

EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:

a=np.random.rand()
print(a)#random is a sub pacakage of numpy

0.9669822517533474


In [ ]:
a=np.random.randint(0,3)
print(a)

0


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
import numpy as np
a=np.arange(0,24).reshape(3,4,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [ ]:
import numpy as np
a=np.array([[1,5],[5,4]])
b=np.array([[1,8],[3,6]])
c=np.dot(a,b)
print(c)

[[16 38]
 [17 64]]


In [ ]:
from numpy import random as rd
a=np.ones((2,3),dtype=int)
#print(a.sum())
#print(a.sum(axis=1))
#print(a.sum(axis=0))



[2 2 2]


a=np.floor(1,2)
print(a)

In [ ]:
c=np.random.random((2,2))
#print(c)
a=np.ceil(np.random.random((2,12)))
a=np.floor(np.random.random((2,12)))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
from numpy import random as rd
a=np.array([[1,5],[5,4]])
b=np.array([[1,8],[3,6]])
#print(a)
#print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min(axis=1))
print(a.min(axis=0))

[5 5]
[5 5]
[1 4]
[1 4]


In [ ]:
from numpy import random as rd
a=np.array([[1,5],[5,4]])
b=np.array([[1,8],[3,6]])
#print(a)
#print(a.max())
print(a.cumsum(axis=1))
print(b.cumsum(axis=1))
#print(a.max(axis=0))
#print(a.min(axis=1))
#print(a.min(axis=0))

[[1 6]
 [5 9]]
[[1 9]
 [3 9]]


a=np.array([2,3,5,6])
print(a.cusum())



In [ ]:
a=np.array([2,3,5,6])
print(a.cumsum())



[ 2  5 10 16]


In [ ]:
a=np.array([2,3,5,6,7,8,8])
a.resize(4,2)
print(a.shape)

(4, 2)


In [ ]:
a=np.array([2,3,5,6,7,8])
a.resize(2,3)
b=np.array([6,1,4,6,7,8])
b.resize(2,3)
#print(np.vstack((a,b)))
print(np.hstack((a,b)))




[[2 3 5 6 1 4]
 [6 7 8 6 7 8]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


number of rows becomes number of group
column becomes rows
group becomes column